### ISSUE TITLE
latex questions

### ISSUE THREAD

**Issue by HinLeung622** [Harry-Westwood/Y4-Project-InterNeuralStellar#41]
@grd349 
In bibtex, how do I turn this:
![image](https://user-images.githubusercontent.com/56083013/77860593-0f497a80-7208-11ea-9451-cba97ded2f36.png)
into this?
![image](https://user-images.githubusercontent.com/56083013/77860621-212b1d80-7208-11ea-9f48-899ee7a4b80f.png)

**Comment by grd349** [comment]
My guess is you used something like the MNRAS style latex file for the top entry but you would rather use something like the APJ (or AAS) style like the bottom example.  Do that make sense?

**Comment by HinLeung622** [comment]
@grd349 
I have not specify any styles, so how exactly do i tell latex to use ALJ or AAS?

**Comment by grd349** [comment]
In which case I wouldn't worry about it :). The format of the bibtex is
worth less than 10^-10 of a mark ;)

G

*Dr Guy R. Davies*
PI - ERC CartographY Project
Senior Lecturer in Astrophysics
School of Physics and Astronomy
The University of Birmingham
Edgbaston
Birmingham  B15 2TT

Tel +44 (0) 121 414 4597
G.R.Davies@bham.ac.uk
grd349@gmail.com
davies@bison.ph.bham.ac.u <davies@bison.ph.bham.ac.uk>k
<davies@bison.ph.bham.ac.uk>

The contents of this e-mail may be privileged and are confidential. It may
not be disclosed, used, or copied in any way by anyone other than the
addressee. If received in error please notify the sender then delete it
from your system. Should you communicate with the sender by e-mail, you
consent to The University of Birmingham monitoring and reading any such
correspondence.

**Comment by HinLeung622** [comment]
@grd349 
The problem is not the mark or style, but rather ApJ’s style does not include the papers’ title and uses much less words. It will help me massively in cutting down the word count to be within 8800 words, considering i have 4 pages of references

**Comment by grd349** [comment]
Exclude the references from the word count!

G

*Dr Guy R. Davies*
PI - ERC CartographY Project
Senior Lecturer in Astrophysics
School of Physics and Astronomy
The University of Birmingham
Edgbaston
Birmingham  B15 2TT

Tel +44 (0) 121 414 4597
G.R.Davies@bham.ac.uk
grd349@gmail.com
davies@bison.ph.bham.ac.u <davies@bison.ph.bham.ac.uk>k
<davies@bison.ph.bham.ac.uk>

The contents of this e-mail may be privileged and are confidential. It may
not be disclosed, used, or copied in any way by anyone other than the
addressee. If received in error please notify the sender then delete it
from your system. Should you communicate with the sender by e-mail, you
consent to The University of Birmingham monitoring and reading any such
correspondence.

**Comment by HinLeung622** [comment]
@grd349 
But according to project guidelines:
“We recommend that the report should be approximately 8000 words including references and table/figure captions but 
excluding any Appendices.”
References are included in word count...

**Comment by grd349** [comment]
How many words do the references contribute?

**Comment by HinLeung622** [comment]
@grd349 
I don't know how to count the references' word count since texcount doesn't count it, and I have no idea how the university counts it either, but if I were to naively just throw it into MS word, it returns around 1300 words, which if I am able to cut down by 60% with removing title and using short forms of journals, will help me by 700 words.

**Comment by HinLeung622** [comment]
@grd349 
sidenote: my current word count (only including main text, headers and captions) is 8891, and I have not written abstract, introduction or the pseudo-cluster validation parts, which will likely add at least 1500 more words, plus references that's 11000+ words haha... The guideline's maximum is 8800.
