### ISSUE TITLE
Calculating Gaia colours

### ISSUE THREAD

**Issue by HinLeung622** [Harry-Westwood/Y4-Project-InterNeuralStellar#42]
@grd349 
Yes it is after the project is done now, but I am interested in further work on the project, so I started messing around with putting the [Teff+L -> absolute G mag+G-Grp colour] calculation into the HBm today, which will give waaaaaaay more stars than what we had for clusters like NGC 188, but I ran into some issues when calculating G-Grp from Gaia:
![image](https://user-images.githubusercontent.com/56083013/78584392-0ff99680-7830-11ea-89ba-e9a77a3cbcdc.png)
This is a plot in (reddening adjusted) colour (Gband - Grp) in x-axis vs absolute G band mag of NGC 6819. My question is why are the blue dots (new calculations) not matching the red dots (old calculations)?
 The grey dots (training data) and red dots (our previous data with Teffs obtained directly from literature) are calculated into the currently CMD by using equations following on luminosity:
G=M_bol,sun - 2.5log10(L/Lsun) - BC
where BC is calculated just as before, from the relations in René Andrae et al. 2018 (Gaia Apsis paper) that only depends on Teff. 
I fit a 2nd order polynomial to the colour-Teff conversion of G-Grp given in https://www.pas.rochester.edu/~emamajek/EEM_dwarf_UBVIJHK_colors_Teff.txt by Eric Mamajek:
![image](https://user-images.githubusercontent.com/56083013/78585488-e2155180-7831-11ea-9ff8-be36c253b143.png)
and use that polynomial to turn Teff into G-Grp from the training (grey) and previous (red) data.

Colour of the blue new dots are calculated from simply:
M_G-M_Grp
where both are absolute magnitudes, given by:
M_G = m_G - dist_mod - A_G
M_Grp = m_Grp - dist_mod - A_Grp
where the extinctions are obtained from Green's dustmap multiplied by coefficients in Jason L. Sanders et al. 2018 (the same source we used before, but now also using R(lambda) for Grp).
And the two don't seem to match up. But it is quite obvious that the new blue dots are the ones in the wrong.

It is fine if you are slow on replies, after all this is no pressing issue.

**Comment by grd349** [comment]
Hi @HinLeung622 

I'm a touched snowed under at the mo -  I missed what you are trying to do ... are you trying to get a proxy for Teff from Gaia.  Most people use the BpRp which would be the ratio of the apparent G_bp to the apparent G_rp bands in Gaia.   Is the along the lines of what you are trying?

**Comment by HinLeung622** [comment]
@grd349 
I am trying to do what I said before when writing the report that could be improved on in our project, that is to shift our observables used in the HBM, from the luminosity-Teff level, to closer to actual observed values, that is absolute colour and absolute G band magnitudes that I am trying.

The reason I did not go for Gbp-Grp even though that is what I initially thought, is that René Andrae et al. 2018 wrote they used Gbp-G and G-Grp instead of Gbp-Grp due to the first two including the more accurately recorded G band mags. So I thought I would follow.

**Comment by grd349** [comment]
Why absolute in two bands?  Do you not want a sequence that goes ... 

proposed [Teff, L, R, whatever] 
   -> Intermediate [Absolute magnitude in say G]
         -> [Observed distance, apparent magnitude, ...]

I'm probably missing something :)

G

**Comment by HinLeung622** [comment]
@grd349 
Yeah sorry for my bad wording, what I mean by absolute colour is the extinction/reddening adjusted colour between two bands.

And yes, if we separate the HBM observables into three levels, they would be:
[Teff, L, R, Fe/H]
[Absolute G, extinction/reddening adjusted Gbp-Grp]
[apparent magnitudes]

And right now I am trying to use the middle layer.
To convert from the middle layer to the bottom layer, I will need to add in distance and extinction into the HBM too, which I thought might just be further complications for the sampler, so I went for the middle layer instead.

All of this is just me thinking about it myself, I hope it is at least sensible.

**Comment by grd349** [comment]
Why do you need ... extinction/reddening adjusted Gbp-Grp ?

**Comment by HinLeung622** [comment]
@grd349 
Emm, isn't that the correct way to do it? Sorry if I am being terribly wrong here, so how exactly should I do it?

**Comment by grd349** [comment]
This just might be the way you are describing the process but normally we would treat extinction/reddening as being something that happens to the apparent magnitudes rather than to the absolutes.  Does that make sense?

**Comment by HinLeung622** [comment]
@grd349 
Yeah that is how I am calculating them. To prevent further confusion, I will write down the full process of how I calculate them below:
M_G = absolute G mag
m_G = apparent G mag
A_G = extinction in G mag
E(B-V) = reddening given by Green's dustmap
R(lambda)_G = extinction coefficient of G band from Sanders et al 2018
r = distance
same for bp and rp

On the apparent mags to absolute mags side:
dist_mod = 5 * log10(r) - 5
A_G = R(lambda)_G * E(B-V)
M_G = m_G - dist_mod - A_G

A_Bp = R(lambda)_Bp * E(B-V)
M_Bp = m_Bp - dist_mod - A_Bp

A_Rp = R(lambda)_Rp * E(B-V)
M_Rp = m_Rp - dist_mod - A_Rp

colour(Bp-Rp) = M_Bp-M_Rp

On the luminosity/Teff to absolute mags side:
Teff -> colour(Bp-Rp) by colour-Teff conversions given in https://www.pas.rochester.edu/~emamajek/EEM_dwarf_UBVIJHK_colors_Teff.txt by Eric Mamajek
val = Teff - Teff_Sun
BC_G = a0+(a1*val)+(a2*val**2)+(a3*val**3)+(a4*val**4) (coefficients from Andrea et al. 2018)
M_G = M_bol,sun - 2.5 * log10(L/L_sun) - BC_G

Hope that clears things up. Also, do you have a better suggestion for the Teff -> colour conversion than what I am using right now?
